name: check_code_quality

on: pull_request

jobs:
  pylint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: |
          python -m pip install --upgrade pip
          pip install pylint

      - run: |
          pylint app.py
  
  black:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: |
          python -m pip install --upgrade pip
          pip install black

      - run: |
          black --check --verbose .
